app:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: 'jdbc:mysql://localhost:3306/coffeecon'
      username: 'admin'
      password: 'admin'
      pool-size: 30
  aws:
    access_key: 'AKIA5RBAKQEHQXBIB6N3'
    secret_key: 'AKIA5RBAKQEHQXBIB6N3'
    region: 'us-east-1'
    cognito:
      clientId: '6gcp7350aqf93r75ncd3b57q34'
      userPoolId: 'us-east-1_FKWar0dk4'
      region: 'us-east-1'
      connectionTimeout: 2000
      readTimeout: 2000
      jwk: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_FKWar0dk4/.well-known/jwks.json
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_FKWar0dk4
logging:
  level:
    org:
      springframework: DEBUG
    com:
      example : DEBUG
server:
  ssl:
    key-store: device.p12
    key-store-password: coffeecon
    key-store-type: pkcs12
  port: 443